/*
 * Room Sense — crash uploader.
 *
 * ESP-IDF can write a coredump (CPU registers + stack snapshot) to a
 * dedicated flash partition on panic. This component, called once at boot,
 * checks whether a coredump is present and if so POSTs it to the backend
 * for offline analysis, then erases the partition so the same dump isn't
 * uploaded repeatedly.
 *
 * Backend endpoint: PUT http://<host>:5050/api/coredump/<board_mac>
 * Body: raw coredump bytes (ELF format generated by ESP-IDF)
 *
 * Backend stores by MAC + boot timestamp. Analysis is offline using
 * espcoredump.py info_corefile.
 *
 * Saves us from having to be physically attached when a board crashes —
 * the rs_temp stack overflow during Phase 4 would have been diagnosable
 * remotely if this had been in place.
 */
#pragma once

#ifdef __cplusplus
extern "C" {
#endif

/* If a coredump is present in flash, upload it to the backend and erase
 * it. No-op if no coredump exists. Safe to call after WiFi STA is up. */
void rs_crash_upload_if_present(void);

#ifdef __cplusplus
}
#endif
